# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afd0726c984c6674524a4f086a66d59d2c883e917712e7a2323c7abb350aa1d31e969a0b87b0e9f4819ced8dcf279944797f31ebbbb33b1a7b25f036f66e7a57

test:
  secret_key_base: 21c8f209b495fd6a2684479f8dc028883a52a3754507338a95061b7d312c94341094d9a07c06cd74f2ffd84bf206f9ec5d992c17b2c51b520f3a686f45970cc2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
